internal sealed partial class CalculateSectionIdCommand
{
    private static readonly Dictionary<char, int> CharLookup = new()
    {
        {'A', 5 },
        {'B', 6 },
        {'C', 7 },
        {'D', 8 },
        {'E', 9 },
        {'F', 0 },
        {'G', 1 },
        {'H', 2 },
        {'I', 3 },
        {'J', 4 },
        {'K', 5 },
        {'L', 6 },
        {'M', 7 },
        {'N', 8 },
        {'O', 9 },
        {'P', 0 },
        {'Q', 1 },
        {'R', 2 },
        {'S', 3 },
        {'T', 4 },
        {'U', 5 },
        {'V', 6 },
        {'W', 7 },
        {'X', 8 },
        {'Y', 9 },
        {'Z', 0 },
        {'a', 7 },
        {'b', 8 },
        {'c', 9 },
        {'d', 0 },
        {'e', 1 },
        {'f', 2 },
        {'g', 3 },
        {'h', 4 },
        {'i', 5 },
        {'j', 6 },
        {'k', 7 },
        {'l', 8 },
        {'m', 9 },
        {'n', 0 },
        {'o', 1 },
        {'p', 2 },
        {'q', 3 },
        {'r', 4 },
        {'s', 5 },
        {'t', 6 },
        {'u', 7 },
        {'v', 8 },
        {'w', 9 },
        {'x', 0 },
        {'y', 1 },
        {'z', 2 },
        {'`', 6 },
        {'~', 6 },
        {'!', 3 },
        {'@', 4 },
        {'#', 5 },
        {'$', 6 },
        {'%', 7 },
        {'^', 4 },
        {'&', 8 },
        {'*', 2 },
        {'(', 0 },
        {')', 1 },
        {'-', 5 },
        {'_', 5 },
        {'=', 1 },
        {'+', 3 },
        {'\\', 2 },
        {'\t', 5 },
        {'[', 1 },
        {'{', 3 },
        {']', 3 },
        {'}', 5 },
        {';', 9 },
        {':', 8 },
        {'\'', 9 },
        {'\"', 4 },
        {',', 4 },
        {'<', 0 },
        {'.', 6 },
        {'>', 2 },
        {'/', 7 },
        {'?', 3 },
        {' ', 2 },
        {'0', 8 },
        {'1', 9 },
        {'2', 0 },
        {'3', 1 },
        {'4', 2 },
        {'5', 3 },
        {'6', 4 },
        {'7', 5 },
        {'8', 6 },
        {'9', 7 }
    };

    private static readonly Dictionary<string, CharacterClass> CharacterClassLookup = new(StringComparer.OrdinalIgnoreCase)
    {
        {"HUmar", new CharacterClass("HUmar", 5, "red") },
        {"HUnewearl", new CharacterClass("HUnewearl", 6, "red") },
        {"HUcast", new CharacterClass("HUcast", 7, "red") },
        {"HUcaseal", new CharacterClass("HUcaseal", 4, "red") },
        {"RAmar", new CharacterClass("RAmar", 8, "green") },
        {"RAmarl", new CharacterClass("RAmarl", 6, "green") },
        {"RAcast", new CharacterClass("RAcast", 9, "green") },
        {"RAcaseal", new CharacterClass("RAcaseal", 0, "green") },
        {"FOmar", new CharacterClass("FOmar", 5, "blue") },
        {"FOmarl", new CharacterClass("FOmarl", 1, "blue") },
        {"FOnewm", new CharacterClass("FOnewm", 2, "blue") },
        {"FOnewearl", new CharacterClass("FOnewearl", 3, "blue") },
    };

    private static readonly Dictionary<int, SectionId> SectionIdLookup = new()
    {
        {0, new SectionId("Viridia", 0, "#00ab6b") },
        {1, new SectionId("Greenill", 1, "#72fa3f") },
        {2, new SectionId("Skyly", 2, "#6cfeff") },
        {3, new SectionId("Bluefull", 3, "#3f92fc") },
        {4, new SectionId("Purplenum", 4, "#ce00ff") },
        {5, new SectionId("Pinkal", 5, "#ff8bc7") },
        {6, new SectionId("Redria", 6, "#f70811") },
        {7, new SectionId("Oran", 7, "#fe9411") },
        {8, new SectionId("Yellowboze", 8, "#ffff00") },
        {9, new SectionId("Whitill", 9, "#ffffff") },
    };
}
